// Ionicons (https://ionicons.com/)
export const ICONS = {
  add: "add-outline",
  alarm: "alarm-outline",
  arrow_down: "chevron-down-outline",
  arrow_up: "chevron-up-outline",
  change_password: "lock-closed-outline",
  check: "checkmark-outline",
  clone: "add-circle-outline",
  close: "close-outline",
  create: "create-outline",
  credits: "people-outline",
  done: "checkmark-done-outline",
  edit: "pencil-outline",
  ellipsis_h: "ellipsis-horizontal",
  ellipsis_v: "ellipsis-vertical",
  eye_off: "eye-off-outline",
  eye_on: "eye-outline",
  formula: "book-outline",
  go: "arrow-forward-outline",
  information: "information-circle-outline",
  ingredient: "reader-outline",
  language: "language-outline",
  list: "list-outline",
  options: "options",
  play: "play",
  production: "flame-outline",
  production_play: "play-circle",
  production_start: "play-circle-outline",
  production_stop: "stop-circle-outline",
  settings: "settings-outline",
  share: "share-outline",
  sign_out: "log-out-outline",
  thermometer: "thermometer-outline",
  timer: "timer-outline",
  trash: "trash-outline",
  water: "water",
};
