export const ICONS = {
  add: "add-outline",
  arrow_down: "chevron-down-outline",
  arrow_up: "chevron-up-outline",
  change_password: "lock-closed-outline",
  clone: "add-circle-outline",
  close: "close-outline",
  create: "create-outline",
  credits: "people-outline",
  ellipsis_h: "ellipsis-horizontal",
  ellipsis_v: "ellipsis-vertical",
  formula: "book-outline",
  information: "information-circle-outline",
  ingredient: "reader-outline",
  language: "language-outline",
  options: "options",
  production: "flame-outline",
  settings: "settings-outline",
  share: "share-outline",
  sign_out: "log-out-outline",
};
